export const GET_COINS = "GET_COINS";
export const GET_CACHED_COINS = "GET_CACHED_COINS";
export const GET_FILTERED_COINS = "GET_FILTERED_COINS";
export const GET_DETAILS = "GET_DETAILS";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const GET_USER_COINS = "GET_USER_COINS";
export const ADD_CURRENT_COIN = "ADD_CURRENT_COIN";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
